# Generated by Django 4.1.9 on 2023-06-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_post_tablegames_videogames'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogames',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
