# Generated by Django 4.1.9 on 2023-06-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_tablegames_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
