# Generated by Django 4.1.9 on 2023-06-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablegamesN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreT', models.CharField(max_length=200)),
                ('descripcionT', models.TextField()),
                ('precioT', models.IntegerField()),
                ('imagenT', models.ImageField(null=True, upload_to='productos')),
                ('published_dateT', models.DateTimeField(blank=True, null=True)),
                ('marcaT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.marca')),
            ],
        ),
    ]
