# Generated by Django 4.1.9 on 2023-06-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_tablegamesn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablegamesN',
        ),
    ]
